[package]
name = "schema_validation"
version = "0.0.1"
authors = ["kaichao <kaichaosuna@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]
name = "schema_validation"

[dependencies]
derive_more = "0"
serde = "1"
hdk = "0.0.103"